### ISSUE TITLE
3 way conference calling

### ISSUE THREAD

**Issue by JsutterIntulse** [intulse/client-beta#21]
Develop 3-way or "ad-hoc" conference calling to Intulse App, both on mobile and desktop

**Describe the solution you'd like**
Develop 3-way or "ad-hoc" conference calling to Intulse App, both on mobile and desktop

**Describe alternatives you've considered**
You can place callers into a conference room one at a time, but it's not ideal

**Comment by darrenhollick** [comment]
I can agree with the concept let's describe with some detail how we think this should work.
