### ISSUE TITLE
Special Characters in Organization name

### ISSUE THREAD

**Issue by JsutterIntulse** [intulse/client-beta#36]
**Describe the bug [required]**
If an organization name has an apostrophe in it you can not Impersonate the client. Not sure if this affects normal logins.

**To Reproduce [required]**
1. Add an apostrophe or find an organization with an apostrophe in it
2. Click on  Impersonate for any user in the Account center in that organization

**Expected behavior [required]**
It logs you in as that user

**Actual behavior [required]**
It does not log you and produces console error indicating that a character is outside the "Latin" range

**Additional context**
We should ensure we escape all special charcters.

**Comment by darrenhollick** [comment]
Search and replace "Word" apostrophy's with regular ones for all clients

**Comment by gdalam** [comment]
We believe this was caused by the quote being a bad quote (Word quote, smart quote, whatever). Doesn't look like there are any more in the database.

```
SELECT * FROM Organizations
WHERE (Name LIKE '%' + CHAR(145) + '%')
	OR (Name LIKE '%' + CHAR(146) + '%')
```

You can use the above script to check for org's with bad quotes in the name, it should instead be `CHAR(39)`
