### ISSUE TITLE
Updating Extension Names

### ISSUE THREAD

**Issue by JsutterIntulse** [intulse/client-beta#43]
**Describe the bug [required]**
If you update an extension on the server and then attempt to update that name change on a device the name does not update unless you change the extension, then change it back or manually change the extension name in the CFG

**To Reproduce [required]**
1. Update an extension name that is already assigned to a device
2. log into the account center and scan the server
3. Go to the device that needs updating
4. Click save and update

**Expected behavior [required]**
The extension name on the device will update to the name change from the server

**Actual behavior [required]**
The extension name does not change. This is reflected in the CFG file as the label still displays the old name for the extension

**Comment by darrenhollick** [comment]
We want to fix this before release.  The "fix" is going to be that every time the editor loads it should SET the account labels to be based on the matched extension.
