### ISSUE TITLE
User Save behavior

### ISSUE THREAD

**Issue by JsutterIntulse** [intulse/client-beta#44]
**Describe the bug [required]**
When managing a user in the account center, once you hit save there is little to no feedback that the changes have been saved.

**To Reproduce [required]**
1. Go to Users- Manage
2. Click on a user to edit them
3. Make some changes to any info
4. Click Save

**Expected behavior [required]**
Some user feedback is provided that the user info is saved. Such as a message or by taking you back to the User- Manage Screen. 

**Actual behavior [required]**
The save button swirls for half a second.

**Comment by darrenhollick** [comment]
We should automatically return them to the list of users after a successful save.

**Comment by gdalam** [comment]
Darren says this is done
