### ISSUE TITLE
Meetings does not show when no conference rooms

### ISSUE THREAD

**Issue by JsutterIntulse** [intulse/client-beta#49]
**Describe the bug [required]**
If you do not have any conference rooms configured in the dashboard the meetings section will not load. 

**To Reproduce [required]**
1. Configure a server that does not have any conference audio Bridges setup
2. Log into the dashboard with a user that has a Meetings license assigned to them
3. Go to Conferences screen

**Expected behavior [required]**
Meetings section loads

**Actual behavior [required]**
Meetings section does not load

**Comment by ZZBrent** [comment]
Looking into this now

**Comment by gdalam** [comment]
This is fixed, not sure when that happened
